Achievement 2/exercise2.8/A2_Recipe_App/src/recipe/urls.py
from django.urls import path
from .views import YourRecipesView
from .views import RecipeDetailView
from .views import RecipeHome
from .views import RecipeSearchView
from .views import RecipeCreateView, IngredientAddView, RecipeDeleteView

app_name = "recipe"


urlpatterns = [
    path("", RecipeHome.as_view(), name="home"),
    path("your_recipes/", YourRecipesView.as_view(), name="your_recipes"),
    path("detail/<pk>", RecipeDetailView.as_view(), name="detail"),
    path("search/", RecipeSearchView.as_view(), name="search"),
    path("create/", RecipeCreateView.as_view(), name="create"),
    path(
        "add_ingredient/<int:pk>/", IngredientAddView.as_view(), name="add_ingredient"
    ),
    path("delete/<int:pk>/", RecipeDeleteView.as_view(), name="delete"),
]

Achievement 2/exercise2.8/A2_Recipe_App/src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view
from customuser.views import (
    register_user,
    your_profile,
    success
)  

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipe.urls")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", register_user, name="register"),  # Add this URL pattern
    path("your_profile/", your_profile, name="your_profile"),
    path("success/", success, name="success"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Achievement 2/exercise2.8/A2_Recipe_App/src/recipe/models.py
from django.db import models
from django.shortcuts import reverse
from customuser.models import CustomUser 

RECIPE_TYPES = (
    ("breakfast", "Breakfast"),
    ("lunch", "Lunch"),
    ("dinner", "Dinner"),
    ("appetizer", "Appetizer"),
    ("dessert", "Dessert"),
    ("snack", "Snack"),
    ("drink", "Drink"),
    ("cocktail", "Cocktail"),
    ("other", "Other"),
)


class Recipe(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, unique=True)
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="recipes",
    )
    recipe_ingredients = models.ManyToManyField(
        "recipeingredient.RecipeIngredient",
        through="recipeingredientintermediary.RecipeIngredientIntermediary",
    )
    directions = models.TextField()
    cooking_time = models.PositiveIntegerField(null=True, blank=False)
    star_count = models.PositiveIntegerField(
        choices=[(i, i) for i in range(1, 6)], null=True, blank=False
    )
    recipe_type = models.CharField(max_length=100, choices=RECIPE_TYPES, blank=False)
    adapted_link = models.URLField(blank=True, null=True, default=None)
    servings = models.PositiveIntegerField(null=True, blank=False)
    yield_amount = models.IntegerField(blank=True, null=True, default=None)
    allergens = models.TextField(
        blank=True,
    )
    small_desc = models.TextField(
        max_length=200, default="No Description has been added currently."
    )
    pic = models.ImageField(upload_to="recipe", default="no_picture.jpg")

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("recipe:detail", kwargs={"pk": self.pk})

    def calculate_difficulty(self):
        try:
            ingredients_len = len(self.recipe_ingredients.all())
            if self.cooking_time < 10 and ingredients_len < 4:
                return "Easy"
            elif self.cooking_time < 10 and ingredients_len > 4:
                return "Medium"
            elif self.cooking_time >= 10 and ingredients_len < 4:
                return "Intermediate"
            elif self.cooking_time >= 10 and ingredients_len >= 4:
                return "Hard"
        except:
            print("Missing an appropriate cooking time or ingredients.")
            return "Missing cooking time or ingredients."

Achievement 2/exercise2.8/A2_Recipe_App/src/recipe/forms.py
from collections import OrderedDict
from django import forms  # import django forms
from recipeingredientintermediary.models import RecipeIngredientIntermediary
from .models import Recipe
from django.core.validators import MinValueValidator

SEARCH__CHOICES = (  # specify choices as a tuple
    (
        "#1",
        "Search by Your Recipes",
    ),
    ("#2", "Search by All Recipes"),
    ("#3", "Show All Recipes"),
)
AMOUNT_TYPES = (
    ("cup", "Cup"),
    ("teaspoon", "Teaspoon"),
    ("tablespoon", "Tablespoon"),
    ("fluid ounce", "Fluid Ounce"),
    ("pint", "Pint"),
    ("quart", "Quart"),
    ("gallon", "Gallon"),
    ("milliliter", "Milliliter"),
    ("liter", "Liter"),
    ("ounce", "Ounce"),
    ("pound", "Pound"),
    ("gram", "Gram"),
    ("kilogram", "Kilogram"),
    ("each", "Each"),
    ("other", "Other"),
)


class RecipeSearchForm(forms.Form):
    search_mode = forms.ChoiceField(choices=SEARCH__CHOICES)
    search = forms.CharField(max_length=150, required=False)


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        exclude = [
            "user",
            "recipe_ingredients",
        ]  # Exclude user and recipe_ingredient fields from the form

    def save(self, commit=True, user=None):
        instance = super().save(commit=False)
        if user:
            instance.user = user
        if commit:
            instance.save()
        return instance


class RecipeIngredientIntermediaryForm(forms.ModelForm):
    recipe_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    # Add the fields from RecipeIngredient
    ingredient = forms.CharField(max_length=255)
    calorie_content = forms.DecimalField(max_digits=8, decimal_places=2)
    amount = forms.DecimalField(
        max_digits=8, decimal_places=2, validators=[MinValueValidator(0)]
    )
    amount_type = forms.ChoiceField(choices=AMOUNT_TYPES)
    cost = forms.DecimalField(
        max_digits=8, decimal_places=2, validators=[MinValueValidator(0)]
    )
    supplier = forms.CharField(max_length=255)
    grams = forms.DecimalField(
        max_digits=8, decimal_places=2, validators=[MinValueValidator(0)]
    )

    class Meta:
        model = RecipeIngredientIntermediary
        exclude = ["recipe", "recipe_ingredient"]  # Exclude the foreign key fields

Achievement 2/exercise2.8/A2_Recipe_App/src/recipe/views.py
import json
from django.views.generic import ListView, DetailView, FormView
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RecipeForm, RecipeSearchForm, RecipeIngredientIntermediaryForm
import pandas as pd
from .utils import get_recipe_from_title, get_chart
from django.shortcuts import render
from django.utils.html import format_html
from .models import Recipe
from django.views.generic.edit import CreateView
from recipeingredient.models import RecipeIngredient
from ingredient.models import Ingredient
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import DeleteView


class RecipeHome(ListView):
    model = Recipe
    template_name = "recipe/recipes_home.html"

    def get_queryset(self):
        queryset = super().get_queryset()

        for recipe in queryset:
            recipe.title = get_recipe_from_title(recipe.title)

        return queryset


class YourRecipesView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = "recipe/your_recipes.html"

    def get_queryset(self):
        ## function get_queryset is automatically called by ListView and get the request
        # user and filters recipes by username.
        user = self.request.user
        queryset = Recipe.objects.filter(user=user)

        return queryset


def format_cost(cost):
    return f"${cost:.2f}"


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipe/recipe_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Extract ingredient names from the RecipeIngredient objects
        try:
            ingredients = [
                ing.ingredient.name
                for ing in context["object"].recipe_ingredients.all()
            ]

            # Create a dictionary with ingredient names as keys
            ingredient_data = {ingredient: None for ingredient in ingredients}

            df = pd.DataFrame.from_dict(
                ingredient_data, orient="index", columns=["Calorie Content"]
            )

            # Set the 'Calorie Content', 'Grams' and 'Cost' for each ingredient
            for ing in context["object"].recipe_ingredients.all():
                df.loc[ing.ingredient.name, "Calorie Content"] = ing.calorie_content
                df.loc[ing.ingredient.name, "Grams"] = ing.grams
                df.loc[ing.ingredient.name, "Cost"] = format_cost(float(ing.cost))

            # Convert the DataFrame to HTML
            df_html = df.to_html(
                classes="table table-bordered table-hover", escape=False
            )

            # Manually add the table ID to the generated HTML
            df_html = df_html.replace("<table", '<table id="ingredient-info-table"')
            context["recipe_dataframe"] = df_html

            # Get the chart HTML using the get_chart
            chart1 = get_chart("#1", df, x=df.index, y="Calorie Content")
            chart2 = get_chart("#2", df, x=df.index, y="Grams")
            chart3 = get_chart("#3", df, x=df.index, y="Cost")

            context["chart1"] = chart1
            context["chart2"] = chart2
            context["chart3"] = chart3
        except Exception as e:
            print("No ingredients: ", str(e))

        return context


class RecipeSearchView(FormView):
    template_name = "recipe/search.html"
    form_class = RecipeSearchForm

    def form_valid(self, form):
        queryset = self.get_queryset(form)

        # Create a dictionary to store recipe titles and their absolute URLs
        recipe_urls = {recipe.title: recipe.get_absolute_url() for recipe in queryset}
        # Convert the recipe_urls dictionary to a JSON string
        recipe_urls_json = json.dumps(recipe_urls)

        # Convert the queryset to a DataFrame
        data = {
            "Recipe Title": [recipe.title for recipe in queryset],
            "Star Count": [recipe.star_count for recipe in queryset],
            "Cooking Time": [recipe.cooking_time for recipe in queryset],
            "Picture": [recipe.pic.url for recipe in queryset],
        }
        df = pd.DataFrame(data)

        # Modify the DataFrame to include the image as an HTML img tag
        df["Picture"] = df["Picture"].apply(
            lambda url: format_html('<img src="{}" width="200px">', url)
        )

        # Convert the modified DataFrame to HTML
        search_results_df = df.to_html(
            classes="table table-bordered table-hover", index=False, escape=False
        )
        # Manually add the table ID to the generated HTML
        search_results_df = search_results_df.replace(
            "<table", '<table id="search-results-table"'
        )

        context = {
            "search_results_df": search_results_df,
            "recipe_urls_json": recipe_urls_json,
        }

        return render(self.request, self.template_name, context)

    def get_queryset(self, form):
        search = form.cleaned_data.get("search")
        search_mode = form.cleaned_data.get("search_mode")

        if search_mode == "#1" and not self.request.user.is_authenticated:
            return Recipe.objects.none()

        queryset = Recipe.objects.all()

        if search_mode == "#1":
            # Filter recipes by the current user's recipes only
            queryset = Recipe.objects.filter(
                user=self.request.user, title__icontains=search
            )
            if search.strip():
                if not queryset.exists():
                    # Filter recipes by the ingredient name
                    queryset = Recipe.objects.filter(
                        user=self.request.user,
                        recipe_ingredients__ingredient__name__icontains=search,
                    )
            else:
                queryset = Recipe.objects.none()

        elif search_mode == "#2":
            # Only filter if the search bar is not blank
            if search.strip():
                queryset = Recipe.objects.filter(title__icontains=search)
                if not queryset.exists():
                    # Filter recipes by the ingredient name
                    queryset = Recipe.objects.filter(
                        recipe_ingredients__ingredient__name__icontains=search
                    )
            else:
                queryset = Recipe.objects.none()

        elif search_mode == "#3":
            queryset = Recipe.objects.all()

        return queryset


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeForm
    template_name = "recipe/recipe_create.html"
    success_url = "/your_recipes"  # Use the actual URL name for success URL

    def form_valid(self, form):
        form.instance.user = (
            self.request.user
        )  # Set the logged-in user as the recipe creator
        return super().form_valid(form)


class IngredientAddView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeIngredientIntermediaryForm
    template_name = "recipe/add_ingredient.html"
    success_url = "/your_recipes"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe_id = self.kwargs.get(
            "pk"
        )  # Assuming 'pk' is the keyword argument in your URL pattern
        context["form"].initial["recipe_id"] = recipe_id

        return context

    def form_valid(self, form):
        recipe_id = form.cleaned_data["recipe_id"]
        recipe = Recipe.objects.get(id=recipe_id)  # Get the Recipe object
        ingredient_name = form.cleaned_data["ingredient"]

        try:
            ingredient = Ingredient.objects.get(name=ingredient_name)
        except Ingredient.DoesNotExist:
            ingredient = Ingredient(name=ingredient_name)
            ingredient.save()

        recipe_ingredient = RecipeIngredient()
        recipe_ingredient.ingredient = ingredient
        recipe_ingredient.calorie_content = form.cleaned_data["calorie_content"]
        recipe_ingredient.amount = form.cleaned_data["amount"]
        recipe_ingredient.amount_type = form.cleaned_data["amount_type"]
        recipe_ingredient.cost = form.cleaned_data["cost"]
        recipe_ingredient.supplier = form.cleaned_data["supplier"]
        recipe_ingredient.grams = form.cleaned_data["grams"]
        recipe_ingredient.save()

        recipe_ingredient_intermediary = form.save(commit=False)
        recipe_ingredient_intermediary.recipe = recipe
        recipe_ingredient_intermediary.recipe_ingredient = recipe_ingredient
        recipe_ingredient_intermediary.save()

        return super().form_valid(form)


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipe/delete.html"
    success_url = reverse_lazy("recipe:your_recipes")

Achievement 2/exercise2.8/A2_Recipe_App/src/recipe/templates/recipe/add_ingredient.html
{% extends "recipe/recipes_home.html" %}
{% load static %}
{% load custom_filters %}

{% block main %}
<div class="row" style="margin-top: 206px; text-align: center; justify-content: center; align-items: center;">
    <div class="col-2"></div>
    <div class="col-10">
        <main>
            <section class="container"
                style="padding-left: 70px; padding-right: 70px; padding-bottom: 20px; height: auto; color: white">
                <form method="post" style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; 
                justify-content: left; text-align: left; align-items: left;">

                    {% csrf_token %}

                    {{ form.recipe_id }}
                    {% for field in form.visible_fields %}

                    <div
                        style="display: flex; background-color:#2F2332; padding: 10px; border-radius: 5px; border-radius: 5px;">
                        <label style="min-width: 102px;">{{ field.label_tag }}</label>
                        {{ field }}
                    </div>
                    {% endfor %}

                    <button class="btn btn-primary" type="submit"
                        style="grid-column: span 2; height: 100px; margin-left: 15%; margin-right: 15%;">Add
                        Ingredient</button>
                </form>
            </section>
        </main>
    </div>
</div>
{% endblock %}

{% block welcome_script %}
{% endblock %}

Achievement 2/exercise2.8/A2_Recipe_App/src/recipe/templates/recipe/delete.html
{% extends "recipe/recipes_home.html" %}
{% block main %}
<div class="row">
    <div class="col-2"></div>
    <div class="col-10">
        <main style="padding-left: 50px; padding-right: 50px; padding-bottom:30px;
         align-items: center; text-align: center; justify-content: center;">
            <section class="container" style="color: white;">
                <form method="post">
                    {% csrf_token %}
                    <p>Are you sure you want to delete "{{ object }}"?</p>
                    <button class="btn btn-warning" type="submit">Confirm</button>
                </form>
                <a class="btn btn-primary" href="{% url 'recipe:delete' object.pk %}"
                    style="margin-top: 40px">Cancel</a>

            </section>
        </main>
    </div>
</div>
{% endblock %}

{% block welcome_script %}
{% endblock %}

Achievement 2/exercise2.8/A2_Recipe_App/src/recipe/templates/recipe/recipe_create.html
{% extends "recipe/recipes_home.html" %}
{% load static %}
{% load custom_filters %}

{% block main %}
<div class="row" style="margin-top: 206px; text-align: center; justify-content: center; align-items: center;">
    <div class="col-2"></div>
    <div class="col-10">
        <main>
            <section class="container"
                style="padding-left: 70px; padding-right: 70px; padding-bottom: 20px; height: auto; color: white">
                <form method="post" style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; 
                    justify-content: left; text-align: left; align-items: left;">

                    {% csrf_token %}
                    {% for field in form.visible_fields %}
                    <div
                        style="display: flex; background-color:#2F2332; padding: 10px; border-radius: 5px; border-radius: 5px;">
                        <label style="min-width: 102px;">{{ field.label_tag }}</label>
                        {{ field }}
                    </div>
                    {% endfor %}

                    <button class="btn btn-primary" type="submit"
                        style="grid-column: span 2; height: 100px; margin-left: 15%; margin-right: 15%;">Create
                        Recipe</button>
                </form>
            </section>
        </main>
    </div>
</div>
{% endblock %}

{% block welcome_script %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var textareas = document.querySelectorAll("textarea");
        var title = document.getElementsByName("title");
        var pic = document.getElementById("id_pic")

        pic.className += "btn btn-primary";
        pic.style.width = "320px"

        title.forEach((ele) => {
            ele.style.height = "36px"
            ele.style.width = "100%"
        });
        textareas.forEach(function (textarea) {
            textarea.style.height = "100px";
            textarea.style.width = "auto";
        });
    });
</script>
{% endblock %}

Achievement 2/exercise2.8/A2_Recipe_App/src/recipe/templates/recipe/recipes_home.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>

<body style="background:linear-gradient(#3D5038, #151b14)">
    {% block navbar %}
    <header>
        <div class="container">
            <nav class="navbar" style="position:absolute; top:0px; left: 0px; width: 100%">
                <div class="col-4">
                    <img class="img-fluid" style="width:240px; pointer-events: none;"
                        src="../../static/images/tomato-g820ca7bb9_640.png">
                </div>
                <div class="col-5">
                    <form action="{% url 'recipe:search' %}" method="post">
                        {% csrf_token %}
                        {{ search_form.as_p }}
                        <button class="btn btn-primary" type="submit" name="search_btn">Search</button>
                    </form>
                </div>
                <div class="col-3">
                    <div class="btn-group" role="group" aria-label="Button row" id="buttonContainer">
                        {% if user.is_authenticated %}
                        <button type="button" class="btn btn-primary mx-2"><a href="{%url 'logout' %}"> Logout
                            </a></button>
                        <button type="button" class="btn btn-primary mx-2"><a href="{%url 'your_profile' %}">
                                Profile
                            </a></button>
                        {% else %}
                        <button type="button" class="btn btn-primary mx-2"> <a href="{%url 'login' %}"> Login
                            </a></button>
                        <button id="signUpBtn" type="button" class="btn btn-primary mx-2" data-bs-toggle="popover"
                            data-bs-html="true">
                            <a href="{%url 'register' %}"> Register
                            </a>
                        </button>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </div>
    </header>

    {% endblock %}

    {% block main %}
    <div class="row" style="margin-top: 206px">
        <div class="col-2"></div>
        <div class="col-10">
            <main style="padding-left: 50px; padding-right: 50px; padding-bottom:30px;">
                <section class="container" style="color: white;">
                    {% for object in object_list %}
                    <div class="row">
                        {% if forloop.counter|divisibleby:2 %}
                        <div class="col-5 p-0">
                            <div class="card h-100 card-style" style="border-radius: 0;">
                                <div class="card-body">
                                    <h3 class="card-title card-title-underline card-title-style">
                                        <b>{{object.title}}</b>
                                    </h3>
                                    <p class="card-text card-text-border">{{ object.small_desc}}</p>
                                    <a href="{{object.get_absolute_url}}" class="btn btn-primary">View Recipe</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-7 p-0">
                            <img src="{{object.pic.url}}" class="img-fluid" style="width:auto; max-height: 600px"
                                alt="Recipe Image">
                        </div>
                        {% else %}
                        <div class="col-7 p-0">
                            <img src="{{object.pic.url}}" class="img-fluid" style="width:auto;max-height: 600px;"
                                alt="Recipe Image">
                        </div>
                        <div class="col-5 p-0">
                            <div class="card h-100 card-style" style="border-radius: 0;">
                                <div class=" card-body">
                                    <h3 class="card-title card-title-underline card-title-style">
                                        <b>{{object.title}}</b>
                                    </h3>
                                    <p class="card-text card-text-border">
                                        {{ object.small_desc}}</p>
                                    <a href="{{object.get_absolute_url}}" style="bottom: 0px;"
                                        class="btn btn-primary">View Recipe</a>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                </section>
            </main>
        </div>
    </div>
    {% endblock %}
    {% block footer %}
    <footer>
        <div class="container">
            <nav class="navbar" style="position:absolute; bottom: 15px; left: 0px; width: 100%">
                <div class="col-2">
                    <div class="container text-center">
                        <p>2023 Recipe App.</p>
                    </div>
                </div>
                <div class="col-7"></div>
                <div class="col-3">
                    <div class="btn-group" role="group" aria-label="Button row">
                        <button type="button" class="btn btn-primary mx-2">About</button>
                        <button type="button" class="btn btn-primary mx-2">Contact</button>
                    </div>
                </div>
            </nav>
        </div>
    </footer>
    {% endblock %}

    {% block left-navbar %}
    <div class="left-navigation">
        <ul>
            <li><a href="/" class="btn btn-primary left-nav-button" type="submit">Home</a></li>

            {% if user.is_authenticated %}
            <li><a href="/your_recipes" class="btn btn-primary left-nav-button" type="submit">Your Recipes</a></li>
            <li><a href="/create" class="btn btn-primary left-nav-button" type="submit">Create</a></li>
            <li><a class="btn btn-primary left-nav-button" type="submit">Edit</a></li>
            {% else %}
            <li><a class="btn btn-primary left-nav-button" type="submit" hidden>Your Recipes</a>
            </li>
            <li><a class="btn btn-primary left-nav-button" type="submit" hidden>Create</a></li>
            <li><a class="btn btn-primary left-nav-button" type="submit" hidden>Edit</a></li>
            {% endif %}
            </li>
        </ul>
    </div>


    {% endblock %}

    {% block welcome_script %}
    {% if not user.is_authenticated %}
    <div id="signUpPopoverContent" style="display: none;">
        <div>
            <h3>Register</h3>
            <p>Enter your details to register.</p>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function initializePopover() {
            var signUpBtn = document.getElementById('signUpBtn');
            var signUpPopover = new bootstrap.Popover(signUpBtn, {
                content: document.getElementById('signUpPopoverContent').innerHTML,
                boundary: 'viewport',
                placement: 'bottom'
            });

            signUpPopover.show();

            setTimeout(function () {
                signUpPopover.hide();
            }, 5000);
        }
        document.addEventListener('DOMContentLoaded', function () {
            initializePopover();
        });
    </script>
    {% endif %}
    {% endblock %}
</body>

</html>

Achievement 2/exercise2.8/A2_Recipe_App/src/recipe/templates/recipe/your_recipes.html
{% extends "recipe/recipes_home.html" %}
{% load static %}
{% load custom_filters %}

{% block main %}
<div class="row" style="margin-top: 156px">
    <div class="col-2"></div>
    <div class="col-10">
        <main>
            <section class="container" style="padding-bottom: 20px; color: white">
                <div class="row">
                    {% for object in object_list %}
                    <div class="col-md-4">
                        <div class="card" style="min-height: 660px; padding:1px; border: 5px solid black">

                            <img src="{{object.pic.url}}" style="width: 100%; max-height: 240px;" class="card-img-top"
                                alt="Recipe Image">
                            <div class="card-body card-style">
                                <h5 class="card-title card-title-style">
                                    {{object.title}}
                                </h5>
                                <p class="card-text"
                                    style="border:1px solid  #1DE244; border-radius: 3px; word-wrap: break-word; height:120px">
                                    {{object.small_desc}}</p>
                                <p class="card-text"
                                    style="border:1px solid  #1DE244; border-radius: 3px; word-wrap: break-word; height:80px; font-size: small;">
                                    {% for ingredient in object.recipe_ingredients.all %}
                                    {{ ingredient.ingredient }}
                                    {% if not forloop.last %}| {% endif %}
                                    {% endfor %}
                                <div class="row">
                                    <div class="col-6">
                                        <a href="{{object.get_absolute_url}}" class="btn btn-primary"
                                            style="height: 40px; min-width: 140px; font-size: small;">View Recipe</a>
                                    </div>
                                    <div class="col-6">
                                        <a href="{% url 'recipe:add_ingredient' pk=object.pk %}" class="btn btn-primary"
                                            style="height: 40px; min-width: 140px; font-size: small;">Add
                                            Ingredient</a>
                                        <!-- Passing the pk of the clicked recipe to the IngredientAddView URL -->
                                    </div>
                                </div>
                                <div class="row" style="margin-top: 16px;">
                                    <div class="col-6">
                                        <a href="{% url 'recipe:delete' pk=object.pk %}" class="btn btn-primary"
                                            style="height: 40px; min-width: 140px; font-size: small;">Delete Recipe</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    {% endfor %}
                </div>
            </section>
        </main>
    </div>
</div>
{% endblock %}

{% block welcome_script %}
{% endblock %}